### PR TITLE
Unify constant matches

### PR DESCRIPTION
**Pull request by brendanzab**
Somewhere along the line we forgot to add a case for this.

### CODE REVIEW

**Comment by Kmeakin** [comment]
Could we have a more strongly normalizing representation for branches? At the moment I believe these two functions won't unify:

```fathom
let not1 = fun (b : Bool) => match b {
    true => false,
    _ => true,
}

let not2 = fun (b : Bool) => match b {
    false => true,
    _ => false,
}
```

**Comment by brendanzab** [comment]
Hmm, not sure! At the moment the branches are elaborated into a sorted list of cases, but yeah you are right there’s cases where that falls down due to the default branch

**Comment by brendanzab** [comment]
Ahh I see what you mean. Yeah if expressions are currently desugared out of order (fixed that).

**Review by wezm — APPROVED** [review]
Looks good 👍

**Pull request merged**
